---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-user
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "configmaps", "services", "pods", "pods/log"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-user
roleRef:
  kind: Role
  name: cluster-user
  apiGroup: rbac.authorization.k8s.io
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "clusterUser"