---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-read-access
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["watch", "get"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["list","get"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["list","get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-read-access
subjects:
  - kind: ServiceAccount
    name: app-read-access
roleRef:
  kind: Role
  name: app-read-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-read-access
